name: scalpx3
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  web_socket_channel: ^2.2.0
  dio: ^5.0.0
  http: ^1.6.0
  injectable: ^1.5.3
  get_it: ^7.2.0
  web3dart: ^3.0.2
  crypto: ^3.0.3

dev_dependencies:
  injectable_generator:
  build_runner: ^2.3.3
  lints: ^6.0.0
  test: ^1.25.6